definitions:
  models.ReqDepositList:
    properties:
      accountHolderId:
        example: 8a8e87bf7c7d97b7017c92cbdcf40abe
        type: string
      accountHolderType:
        example: CLIENT
        type: string
      paginationDetails:
        description: |-
          ID of an item

          In: query
        example: "OFF"
        type: string
    type: object
  models.ResDeposit:
    properties:
      accountHolderKey:
        type: string
      accountHolderType:
        type: string
      accountState:
        type: string
      accountType:
        type: string
      accruedAmounts:
        properties:
          interestAccrued:
            type: integer
          negativeInterestAccrued:
            type: integer
          overdraftInterestAccrued:
            type: integer
          technicalOverdraftInterestAccrued:
            type: integer
        type: object
      approvedDate:
        type: string
      assignedBranchKey:
        type: string
      balances:
        properties:
          availableBalance:
            type: number
          blockedBalance:
            type: number
          feesDue:
            type: integer
          forwardAvailableBalance:
            type: integer
          holdBalance:
            type: number
          lockedBalance:
            type: number
          overdraftAmount:
            type: integer
          overdraftInterestDue:
            type: integer
          technicalOverdraftAmount:
            type: integer
          technicalOverdraftInterestDue:
            type: integer
          totalBalance:
            type: number
        type: object
      creationDate:
        type: string
      currencyCode:
        type: string
      encodedKey:
        type: string
      id:
        type: string
      interestSettings:
        properties:
          interestPaymentSettings:
            properties:
              interestPaymentDates:
                items: {}
                type: array
              interestPaymentPoint:
                type: string
            type: object
          interestRateSettings:
            properties:
              encodedKey:
                type: string
              interestChargeFrequency:
                type: string
              interestChargeFrequencyCount:
                type: integer
              interestRate:
                type: number
              interestRateSource:
                type: string
              interestRateTerms:
                type: string
              interestRateTiers:
                items: {}
                type: array
            type: object
        type: object
      internalControls:
        properties:
          maxWithdrawalAmount:
            type: number
        type: object
      lastModifiedDate:
        type: string
      name:
        type: string
      notes:
        type: string
      overdraftInterestSettings:
        type: object
      overdraftSettings:
        properties:
          allowOverdraft:
            type: boolean
          overdraftLimit:
            type: integer
        type: object
      productTypeKey:
        type: string
      withholdingTaxSourceKey:
        type: string
    type: object
  models.ResExampleSendError:
    properties:
      data: {}
      meta:
        $ref: '#/definitions/response.MetaErrMock'
      response_code:
        example: BC-500
        type: string
      response_message:
        example: Internal Server Error
        type: string
    type: object
  models.ResExampleSendSuccess:
    properties:
      data:
        items:
          $ref: '#/definitions/models.ResDeposit'
        type: array
      meta:
        $ref: '#/definitions/response.Meta'
      response_code:
        example: BC-200
        type: string
      response_message:
        example: Success
        type: string
    type: object
  response.Meta:
    properties:
      debug_param:
        type: string
      trace_id:
        example: 97125121-ea32-4ee0-8706-5b7375e83e94
        type: string
    type: object
  response.MetaErrMock:
    properties:
      debug_param:
        example: Request Time Out
        type: string
      trace_id:
        example: 97125121-ea32-4ee0-8706-5b7375e83e94
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/example/send:
    get:
      consumes:
      - application/json
      description: Example Deposit List Send
      operationId: Example Send
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.ReqDepositList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResExampleSendSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResExampleSendError'
      summary: Example Send
      tags:
      - Example
swagger: "2.0"
