-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS public.m_company
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "companyName" character varying(100) COLLATE pg_catalog."default",
    "companyActive" boolean,
    "companyCreatedAt" timestamp with time zone,
    "companyCreatedBy" character varying(50) COLLATE pg_catalog."default",
    "companyUpdatedAt" timestamp with time zone,
    "companyUpdatedBy" character varying(50) COLLATE pg_catalog."default"
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
