-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS public.t_booking_loan
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "bookingId" character varying(36) COLLATE pg_catalog."default" NOT NULL,
    "customerName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "customerIdentityNo" character varying(16) COLLATE pg_catalog."default",
    "phoneNumber" character varying(15) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    "companyName" character varying(100) COLLATE pg_catalog."default",
    "employeeId" character varying(30) COLLATE pg_catalog."default",
    "installmentId" integer,
    amount numeric,
    status integer DEFAULT 0,
    "taxIdentityImagePath" character varying(50) COLLATE pg_catalog."default",
    "agreeTermsCondition" boolean,
    "bookingCreatedAt" timestamp without time zone,
    "bookingUpdatedAt" timestamp without time zone,
    CONSTRAINT t_booking_loan_pkey PRIMARY KEY (id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
