-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS public.m_installment
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    type character varying(6) COLLATE pg_catalog."default" NOT NULL,
    value smallint NOT NULL,
    "interestRate" numeric,
    "createdAt" timestamp with time zone,
    "createdBy" character varying(30) COLLATE pg_catalog."default",
    "updatedAt" timestamp with time zone,
    "updatedBy" character varying(30) COLLATE pg_catalog."default",
    key character varying(36) COLLATE pg_catalog."default" NOT NULL,
    active boolean,
    CONSTRAINT m_installment_pkey PRIMARY KEY (id, key)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
